### PR TITLE
Update: O(n) Time Complexity O(1) Space Complexity

### PR DESCRIPTION
**Pull request by SwapnanilDhol**
This update optimizes the time and space complexity to O(n) and O(1) respectively.

### CODE REVIEW

**Review by rudrankriyam — CHANGES_REQUESTED** [review]
Thank you Swapnanil for opening the first PR on this repository! Very much appreciated.

Can you add this solution as a different function with a comment that this is an optimised solution? 

For example -
func isPalindromeOptimised(_ head: ListNode?) -> Bool {
    // your solution
}

**Comment by SwapnanilDhol** [comment]
> Thank you Swapnanil for opening the first PR on this repository! Very much appreciated.
> 
> Can you add this solution as a different function with a comment that this is an optimised solution?
> 
> For example -
> func isPalindromeOptimised(_ head: ListNode?) -> Bool {
> // your solution
> }

Will do!

**Review by SwapnanilDhol — COMMENTED** [review]
Does this look good?

**Comment by rudrankriyam** [comment]
Thank you so much @SwapnanilDhol! Keep contributing! :]

**Pull request merged**
